name: Nightly

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/nightly.yml'
  release:
    types: [created]
  schedule:
    - cron: '0 4 * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - id: tag
        name: Get latest tag
        run: |
          tag_name="$(wget -qO- https://api.github.com/repos/msrd0/cargo-doc2readme/releases/latest \
            | jq -r '.tag_name')"
          echo "::set-output name=tag_name::$tag_name"
      - uses: actions/checkout@v3
        with:
          ref: ${{steps.tag.outputs.tag_name}}
      - run: git checkout main -- Dockerfile.nightly
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.nightly
          push: true
          tags: ghcr.io/msrd0/cargo-doc2readme:nightly
